In [285]:
def cost(m, data):
    M = data.shape[0]
#     X = data[]
    num_feat = data.shape[1]-1
    cst=0
    for i in range(M):
        cst+=(1/M)*((data[i][num_feat]-sum(m*data[:,:num_feat][i]))**2)
    print("cost",cst)

In [308]:
def step(data,L_R,m):
    M = data.shape[0]
#     print("M",M)
    num_feat = data.shape[1]-1
    np.set_printoptions(formatter={'float_kind':'{:f}'.format})
#     print("num_feat",num_feat)
    slope_m = np.zeros((data.shape[1]-1,),int)
    for i in range(M):
        x=data[:,:num_feat][i]
        y=data[i][num_feat]
        for j in range(len(slope_m)):
            slope_m[j]+=(-2)*(y-((m*x).sum()))*x[j]
#     for k in range(num_feat):
#         for i in range(M):
#             y = data[i][num_feat]
# #             print("y",y)
#             inner_calc = 0
#             for j in range(num_feat):
#                 x = data[i][j]
# #                 print("x",x)
#                 inner_calc += m[j]*x
# #             print(y,inner_calc,data[i][k],M)
#             slope_m[k] += -((y - inner_calc)*data[i][k]*2)/M
# #             print("slope",slope_m)
    new_m = m - L_R*slope_m
    cost(m,data)
    return new_m

In [309]:
def gd2(data,L_R,no_of_iterations):
    m = np.zeros((data.shape[1]-1,),int)
#     print(data.shape)
#     print(m.shape)
    iterations = no_of_iterations
    while no_of_iterations>0:
        m = step(data,L_R,m)
        no_of_iterations -= 1
    return m

In [310]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
def run() :
    data_train = np.loadtxt("gd_training_boston_x_y_train.csv",delimiter=',')
    data_test = np.loadtxt("gd_test_boston_x_test.csv",delimiter=',')
    print(data_train)
#     print(data_test.shape)
#     print(pd.DataFrame(data_train))
    x_test = data_test
    b = np.ones((data_test.shape[0],1),dtype = int)
#     print(b)
#     print(x_test.shape)
    x_test = np.append(x_test,b,axis=1)
    b = np.ones((data_train.shape[0],),dtype = int)
    data_train = np.insert(data_train,data_train.shape[1]-1,b,axis=1)
#     print(x_test.shape)
    L_R = 0.00001
    no_of_iterations = 1000
    m = gd2(data_train,L_R,no_of_iterations)
    print(m.shape)
    ypred = x_test.dot(m)
    np.set_printoptions(formatter={'float_kind':'{:f}'.format})
    print(ypred.shape)
    print(ypred)
    np.savetxt('yPred_gd_1.csv',ypred)

In [311]:
run()

[[-0.407850 -0.487722 -1.266023 ... 0.410571 -1.097990 37.900000]
 [-0.407374 -0.487722 0.247057 ... 0.291169 -0.520474 21.400000]
 [0.125179 -0.487722 1.015999 ... -3.795795 0.891076 12.700000]
 ...
 [-0.408311 -0.487722 0.247057 ... 0.332066 -0.334043 20.800000]
 [-0.410620 -0.487722 -1.152214 ... 0.203235 -0.744752 22.600000]
 [0.342909 -0.487722 1.015999 ... 0.387875 -1.358713 50.000000]]
cost 599.1222691292876
cost 588.7001510154513
cost 578.6034412947245
cost 568.7877727356126
cost 559.2484959669205
cost 549.9628748901862
cost 540.9156147976148
cost 532.1011452274776
cost 523.499219960447
cost 515.1054504816337
cost 506.9121114987454
cost 498.9017014406603
cost 491.07013330295723
cost 483.41206533246776
cost 475.91926713619824
cost 468.58379640071877
cost 461.40289706436994
cost 454.36794969617273
cost 447.47479979616
cost 440.7200051085202
cost 434.0938184198608
cost 427.5955610765273
cost 421.2206346355764
cost 414.9668408125289
cost 408.8236966384247
cost 402.79716947008217
co

cost 30.109782711832196
cost 30.053503572705228
cost 29.997912824968836
cost 29.943158053497346
cost 29.88924602833979
cost 29.835890937878045
cost 29.78316169658066
cost 29.731087165720446
cost 29.67962761047397
cost 29.628673832446395
cost 29.578280952746255
cost 29.52857995410709
cost 29.47939475409228
cost 29.431102084308527
cost 29.383679368287357
cost 29.33694103803894
cost 29.290692717787536
cost 29.245184463839475
cost 29.200260811695543
cost 29.155748153059978
cost 29.111700931069947
cost 29.068437276645
cost 29.025603091784863
cost 28.9833511632049
cost 28.941640812145977
cost 28.900269459172428
cost 28.859484819331986
cost 28.819294764171897
cost 28.77963416354585
cost 28.740644391216364
cost 28.702224412110354
cost 28.664386834286613
cost 28.627006474858753
cost 28.589986769455038
cost 28.55345702013986
cost 28.517362025816595
cost 28.48162193401574
cost 28.44632841726523
cost 28.411498411235307
cost 28.377138537024376
cost 28.343027575336894
cost 28.30925653059788
cost 28.

cost 25.18491903029891
cost 25.182084580177477
cost 25.17926224843146
cost 25.176449741445076
cost 25.17364724223397
cost 25.17085195163472
cost 25.16808091803685
cost 25.165311875822184
cost 25.162544653853722
cost 25.159788911649148
cost 25.157049064864164
cost 25.154303982278407
cost 25.151555058791143
cost 25.148821317119573
cost 25.146119665785697
cost 25.14343017892002
cost 25.14075751503575
cost 25.13809625664769
cost 25.135428329796184
cost 25.132786879900436
cost 25.13015017010873
cost 25.127516128563038
cost 25.124906452214308
cost 25.122309482815336
cost 25.119717358051382
cost 25.1171455386269
cost 25.114560055643743
cost 25.111976293521717
cost 25.109389823178244
cost 25.106815163972215
cost 25.104248218517213
cost 25.101674728757942
cost 25.09910720011934
cost 25.096536913921806
cost 25.093969799273037
cost 25.091422602684467
cost 25.0888738766021
cost 25.086342146998824
cost 25.08383849309842
cost 25.081321809744058
cost 25.07882162444056
cost 25.076318125165884
cost 25.