In [65]:
def cost(m, data):
    M = data.shape[0]
#     X = data[]
    num_feat = data.shape[1]-1
    cst=0
    for i in range(M):
        cst+=(1/M)*((data[i][num_feat]-sum(m*data[:,:num_feat][i]))**2)
#     print("cost",cst)

In [66]:
def step(data,L_R,m):
    M = data.shape[0]
#     print("M",M)
    num_feat = data.shape[1]-1
#     print("num_feat",num_feat)
    slope_m = np.zeros((data.shape[1]-1,),int)
    for k in range(num_feat):
        for i in range(M):
            y = data[i][num_feat]
#             print("y",y)
            inner_calc = 0
            for j in range(num_feat):
                x = data[i][j]
#                 print("x",x)
                inner_calc += m[j]*x
#             print(y,inner_calc,data[i][k],M)
            slope_m[k] += -((y - inner_calc)*data[i][k]*2)/M
#             print("slope",slope_m)
    new_m = m - L_R*slope_m
    cost(m,data)
    return new_m

In [67]:
def gd2(data,L_R,no_of_iterations):
    m = np.zeros((data.shape[1]-1,),int)
#     print(data.shape)
#     print(m.shape)
    iterations = no_of_iterations
    while no_of_iterations>0:
        m = step(data,L_R,m)
        no_of_iterations -= 1
    return m

In [68]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
def run() :
    data_train = np.loadtxt("gd2_training_ccpp_x_y_train.csv",delimiter=',')
    data_test = np.loadtxt("gd2_test_ccpp_x_test.csv",delimiter=',')
    print(data_train)
    print(data_test.shape)
#     print(pd.DataFrame(data_train))
    x_test = data_test
    b = np.ones((data_test.shape[0],1),dtype = int)
#     print(b)
#     print(x_test.shape)
    x_test = np.append(x_test,b,axis=1)
    b = np.ones((data_train.shape[0],),dtype = int)
    data_train = np.insert(data_train,data_train.shape[1]-1,b,axis=1)
#     print(x_test.shape)
    L_R = 0.0000001
    no_of_iterations = 1000
    m = gd2(data_train,L_R,no_of_iterations)
    print(m.shape)
    ypred = x_test.dot(m)
    np.set_printoptions(formatter={'float_kind':'{:f}'.format})
#     print(ypred.shape)
    print(ypred)
    np.savetxt('yPred_gd_2.csv',ypred)

In [69]:
run()

[[8.580000 38.380000 1021.030000 84.370000 482.260000]
 [21.790000 58.200000 1017.210000 66.740000 446.940000]
 [16.640000 48.920000 1011.550000 78.760000 452.560000]
 ...
 [29.800000 69.340000 1009.360000 64.740000 437.650000]
 [16.370000 54.300000 1017.940000 63.630000 459.970000]
 [30.110000 62.040000 1010.690000 47.960000 444.420000]]
(2392, 4)
(5,)
[455.368314 452.875662 450.387376 ... 452.098755 453.141955 456.187699]
