In [230]:
import numpy as np
from sklearn import datasets
cancer_data = datasets.load_breast_cancer()
cancer_data.data.shape[1]

30

In [231]:
def fit(X_train,Y_train):
    result = {}
    class_values = set(Y_train)
    for current_class in class_values:
        result[current_class]={}
        result["total_data"] = len(Y_train)
        current_class_rows = (Y_train == current_class)
        X_train_current = X_train[current_class_rows]
        Y_train_current = Y_train[current_class_rows]
        result[current_class]["total_count"]= len(Y_train_current)
        num_features = X_train.shape[1]
        for j in range(1,num_features+1):
            j_1 = j-1
            result[current_class][j] = {}
            all_possible_values = set(X_train[:,j_1])
            for current_values in all_possible_values:
#                 print((X_train[:,j_1] == current_values).sum())
                result[current_class][j][current_values]= (X_train[:,j_1] == current_values).sum()
    return result

In [232]:
def probablity(dictionary, x, current_class):
    output = np.log(dictionary[current_class]["total_count"]) - np.log(dictionary["total_data"])
    num_features = len(dictionary[current_class].keys())-1
    for j in range(1, num_features+1):
        xj = x[j-1]
        count_current_class_with_value_xj = dictionary[current_class][j][xj] + 1
        count_current_class = dictionary[current_class]["total_count"] + len(dictionary[current_class][j].keys())
        current_xj_probabiity = np.log(count_current_class_with_value_xj) - np.log(count_current_class)
        output = output + current_xj_probabiity
#     print(output)
    return output

In [233]:
def predictSinglePoint(dictionary, x):
    classes = dictionary.keys()
    best_p = -1000
    best_class = -1
    first_run = True
    for current_class in classes:
        if current_class == "total_data":
            continue
        p_current_class = probablity(dictionary, x, current_class)
        if(first_run or  p_current_class > best_p):
            best_p = p_current_class
            best_class = current_class
        first_run = False
#     print(best_class)
    return best_class

In [234]:
def predict(result, X_test):
    y_pred = []
    for x in X_test:
#         print(x)
        x_class = predictSinglePoint(result,x)
        y_pred.append(x_class)
    return y_pred

In [235]:
def makeLabelled(column):
    second_limit = column.mean()
    first_limit = second_limit * 0.5
    third_limit = second_limit * 1.5
    for i in range(len(column)):
        if column[i]<first_limit:
            column[i] = 0
        elif column[i] > first_limit and column[i]<second_limit:
            column[i] = 1
        elif column[i] > second_limit and column[i]<third_limit:
            column[i] = 2
        else:
            column[i] = 3
    return column

In [236]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target


In [237]:
for i in range(X.shape[-1]):
    X[:,i] = makeLabelled(X[:,i])
print(X)

[[1. 2. 0. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 1. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 1.]
 [1. 2. 1. 0.]
 [1. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [1. 2. 0. 0.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [1. 1. 2. 2.]
 [2. 1. 2. 2.]
 [1. 1. 2. 2.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [2. 1. 2. 2.]
 [1. 1. 2. 2.]
 [1. 1. 1. 1.]
 [2. 1. 2. 2.]
 [2. 1. 2. 1.]
 [2. 1. 2. 2.]
 [1. 1. 1. 2.]
 [2. 2. 2. 2.]
 [1. 1. 2.

In [238]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X,Y, test_size =0.25,random_state=0)

In [239]:
dictionary = fit(X_train,Y_train)

In [240]:
Y_pred = predict(dictionary,X_test)
Y_pred

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [241]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        13
           1       0.42      1.00      0.59        16
           2       0.00      0.00      0.00         9

    accuracy                           0.42        38
   macro avg       0.14      0.33      0.20        38
weighted avg       0.18      0.42      0.25        38

[[ 0 13  0]
 [ 0 16  0]
 [ 0  9  0]]


/Users/apple/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/apple/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/apple/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [242]:
# from sklearn import datasets
# iris = datasets.load_iris()
# X = iris.data
# Y = iris.target
# from sklearn import model_selection
# X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X,Y, test_size =0.25,random_state=0)
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train,Y_train)
y_pred = clf.predict(X_test)
y_pred

array([1, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 0, 1, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [243]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test,y_pred))
print(confusion_matrix(Y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.76      1.00      0.86        16
           2       1.00      0.67      0.80         9

    accuracy                           0.87        38
   macro avg       0.92      0.84      0.86        38
weighted avg       0.90      0.87      0.87        38

[[11  2  0]
 [ 0 16  0]
 [ 0  3  6]]
